#! /usr/bin/env bash

ALTERNATE_BRANCH=data

go build -o /tmp/generate ./generate.go

git checkout -B "$ALTERNATE_BRANCH"

if [ "$(git rev-parse --abbrev-ref HEAD)" = "$ALTERNATE_BRANCH" ]; then
    rm generate.go go.* shell.nix
    /tmp/generate -d ./
    exit 0
else
    echo BUG
    exit 1
fi
