#! /usr/bin/env bash

ALTERNATE_BRANCH=data

go build -o /tmp/generate ./generate.go

git checkout -B "$ALTERNATE_BRANCH"

if [ "$(git rev-parse --abbrev-ref HEAD)" = "$ALTERNATE_BRANCH" ]; then
    rm generate.go go.* shell.nix action
    /tmp/generate -d ./
    git add -A
    git commit -sm "$(date)"
    git push origin "$ALTERNATE_BRANCH" -f
    git checkout master
    git branch -D "$ALTERNATE_BRANCH"
    exit 0
else
    echo BUG
    exit 1
fi
