# This is a basic workflow to help you get started with Actions

name: data-fetch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0/3 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.15.5'
      - name: Setup git
        run: git config --global user.email "lucas59356+gitworker@gmail.com" && git config --global user.name "lucasew's worker"
      - run: ./action
